name: cd

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check version
        run: |
          release=${{ github.ref_name }}
          version=$(uv version --short)
          if [ "$release" != "$version" ]; then
            echo "::error::Git tag and package version don't match!"
            exit 1
          fi

      - name: Create package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
