name: cd

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: poetry

      - name: Install Poetry
        run: pipx install poetry

      - name: Check version
        run: |
          release=${{ github.ref_name }}
          version=$(poetry version -s)
          if [ "$release" != "$version" ]; then
            echo "::error::Git tag and package version don't match!"
            exit 1
          fi

      - name: Create package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
