name: CI

on:
  push:
    branches:
      - "main"
  pull_request: ~

  workflow_dispatch: ~

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: poetry

      - name: Install project
        run: make install

      - name: Run QA
        run: make check

      - name: Test docs generation
        run: make html

  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    needs: [qa]
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python_version: ["3.13", "3.12", "3.11", "3.10", "3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry

      - name: Install project
        run: make install

      - name: Run tests
        run: make test

      - name: Codecov Upload
        if: ${{ matrix.os == 'ubuntu' && matrix.python_version == '3.12' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
