name: Nightly

on:
  schedule:
    - cron: "0 20 * * *"

  workflow_dispatch: ~

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python_version: ["3.12", "3.11", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry

      - name: Install project
        run: make install

      - name: Run tests
        env:
          ADES_TOKEN: ${{ secrets.ADES_TOKEN }}
          ADES_USER: ${{ secrets.ADES_USER }}
        run: make record=rewrite test
