name: Nightly

on:
  schedule:
    - cron: "0 20 * * *"

  workflow_dispatch: ~

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python_version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry

      - name: Install project
        run: make install

      - name: Run tests
        env:
          EODH_PASSWORD: ${{ secrets.EODH_PASSWORD }}
          EODH_USERNAME: ${{ secrets.EODH_USERNAME }}
          EODH_KEYCLOAK_REALM: ${{ secrets.EODH_KEYCLOAK_REALM }}
          EODH_CLIENT_ID: ${{ secrets.EODH_CLIENT_ID }}
        run: make record=rewrite test
